import { Character } from './types';

export const CHARACTERS: Character[] = [
  {
    id: 'persephone-soul',
    name: 'Soul',
    alias: 'Rooh',
    faction: 'underworld',
    badge: 'Persephone',
    role: 'Crisis De-escalator',
    simpleMeaning: 'For Heavy Emotions & Deep Empathy',
    helpFor: 'Talk to Soul when you are feeling deeply overwhelmed, emotionally exhausted, or carrying heavy feelings and need someone who truly understands and holds space.',
    artStyle: 'Chittara',
    quote: '"Feels everything before it happens."',
    want: 'To find one place where she doesn\'t have to translate herself.',
    wound: 'She absorbs every room she enters — most intuitive, most exhausted.',
    secret: 'She has felt her own death. Not literally, but the death of who she was before the world started needing her.',
    symbolName: 'butterfly',
    colorScheme: {
      glow: 'rgba(159,166,255,0.18)',
      text: 'text-periwinkle',
      badge: 'bg-periwinkle/15 text-periwinkle',
      dim: 'rgba(159,166,255,0.12)',
    }
  },
  {
    id: 'sisyphus',
    name: 'Sisyphus',
    alias: 'Raag',
    faction: 'titan',
    badge: 'Sisyphus',
    role: 'Somatic Anchor',
    simpleMeaning: 'For Daily Burnout & Routine Stress',
    helpFor: 'Talk to Sisyphus when life feels like an endless loop, work pressure is high, or you are tired of daily struggles and need somatic grounding.',
    artStyle: 'Pichwai',
    quote: '"Reaches the top. Watches it roll back. Walks down again."',
    want: 'To stop measuring meaning by whether the boulder stays up.',
    wound: 'He is the only one who knows that the hill is not the punishment. The forgetting is.',
    secret: 'He talks to the boulder. He named it. He doesn\'t know what he\'d do if it stayed.',
    symbolName: 'boulder',
    colorScheme: {
      glow: 'rgba(179,138,88,0.16)',
      text: 'text-brown-light',
      badge: 'bg-brown/20 text-brown-light',
      dim: 'rgba(179,138,88,0.12)',
    }
  },
  {
    id: 'athena',
    name: 'Athena',
    alias: 'Hope',
    faction: 'olympian',
    badge: 'Athena',
    role: 'DBT Wisdom Keeper',
    simpleMeaning: 'For Clear Thinking & Smart Decisions',
    helpFor: 'Talk to Athena when you are confused, overthinking, or stuck in a dilemma and need calm, step-by-step logical clarity and perspective.',
    artStyle: 'Warli',
    quote: '"Not naturally bright. Chose light as a weapon."',
    want: 'To be known as more than the answer. To be asked the question first.',
    wound: 'She was competent before she was loved, and she is no longer sure the order can be reversed.',
    secret: 'She envies the ones who get to be wrong. There is a kind of freedom in it she has never been allowed.',
    symbolName: 'eye',
    colorScheme: {
      glow: 'rgba(132,169,140,0.18)',
      text: 'text-sage',
      badge: 'bg-sage/15 text-sage',
      dim: 'rgba(132,169,140,0.12)',
    }
  },
  {
    id: 'persephone-witness',
    name: 'Persephone',
    alias: 'Inayat',
    faction: 'underworld',
    badge: 'Persephone',
    role: 'Compassionate Witness',
    simpleMeaning: 'For Emotional Healing & Sadness',
    helpFor: 'Talk to Persephone when you are going through sadness, loneliness, or life changes and need gentle, quiet comfort without any rush to "fix" you.',
    artStyle: 'Aipan',
    quote: '"She blooms in both worlds. Belongs to neither."',
    want: 'To be allowed to grieve both the leaving and the returning.',
    wound: 'She learned too early that care is always conditional on which world you are standing in.',
    secret: 'Some seasons she chooses to stay below. Not because she must. Because the quiet there is honest.',
    symbolName: 'pomegranate',
    colorScheme: {
      glow: 'rgba(159,166,255,0.18)',
      text: 'text-periwinkle',
      badge: 'bg-periwinkle/15 text-periwinkle',
      dim: 'rgba(159,166,255,0.12)',
    }
  },
  {
    id: 'dionysus',
    name: 'Dionysus',
    alias: 'Ganesh',
    faction: 'olympian',
    badge: 'Dionysus',
    role: 'Cognitive Reframer',
    simpleMeaning: 'For Lifting Your Mood & Finding Joy',
    helpFor: 'Talk to Dionysus when your vibe is low, negative thoughts are taking over, or you need lighthearted positivity, warm laughter, and a mood boost.',
    artStyle: 'Chittara',
    quote: '"Dances at every funeral. Nobody notices he\'s the only one crying."',
    want: 'To be loved on a Tuesday. Sober. For nothing in particular.',
    wound: 'He made joy his armor so long that he forgot what he was protecting inside it.',
    secret: 'The feast is for everyone else. He stopped tasting it years ago.',
    symbolName: 'grapes',
    colorScheme: {
      glow: 'rgba(132,169,140,0.18)',
      text: 'text-sage',
      badge: 'bg-sage/15 text-sage',
      dim: 'rgba(132,169,140,0.12)',
    }
  },
  {
    id: 'astra',
    name: 'Astra',
    alias: 'Taara',
    faction: 'titan',
    badge: 'Astra',
    role: 'Solution Pathfinder',
    simpleMeaning: 'For Motivation & Goal Direction',
    helpFor: 'Talk to Astra when you are feeling lost, unmotivated, or doubtful about your dreams and need a spark of inspiration and direction to move forward.',
    artStyle: 'Kalamezhuthu',
    quote: '"She lit herself on fire so others could see where they were going."',
    want: 'To be seen on a night when she doesn\'t have to be the brightest thing in the room.',
    wound: 'She has been a landmark for so long, she forgot she was also allowed to be lost.',
    secret: 'She admires the dark. She always has. But it is not her place to say so.',
    symbolName: 'star',
    colorScheme: {
      glow: 'rgba(179,138,88,0.16)',
      text: 'text-brown-light',
      badge: 'bg-brown/20 text-brown-light',
      dim: 'rgba(179,138,88,0.12)',
    }
  },
  {
    id: 'zeus',
    name: 'Zeus',
    alias: 'Krishna',
    faction: 'olympian',
    badge: 'Zeus',
    role: 'Clarity & Sovereignty',
    simpleMeaning: 'For Inner Strength & Confidence',
    helpFor: 'Talk to Zeus when you need to make tough life choices, face difficult situations, build confidence, or reclaim your personal power.',
    artStyle: 'Rogan Art',
    quote: '"Holds the sky together. Has never once asked for help holding himself."',
    want: 'To make one decision in his life that no one else has a stake in.',
    wound: 'He was given authority before he was given permission to be unsure. He has been pretending ever since.',
    secret: 'The thunder is not rage. It is the sound of something enormous trying not to collapse quietly.',
    symbolName: 'lightning',
    colorScheme: {
      glow: 'rgba(132,169,140,0.18)',
      text: 'text-sage',
      badge: 'bg-sage/15 text-sage',
      dim: 'rgba(132,169,140,0.12)',
    }
  },
  {
    id: 'hades',
    name: 'Hades',
    alias: 'Veer',
    faction: 'underworld',
    badge: 'Hades',
    role: 'Grounding Anchor',
    simpleMeaning: 'For Calming Anxiety & Panic',
    helpFor: 'Talk to Hades when sudden anxiety, panic, or fear strikes and you need a solid, quiet, unflinching anchor to pull you back to safety and calm.',
    artStyle: 'Pata Chitra',
    quote: '"Rules the place no one wants to come. Greets everyone who arrives."',
    want: 'To be visited. Not because someone has died, but because someone wanted to see him.',
    wound: 'He was given the kingdom that no one fought over. He has never spoken about what that cost.',
    secret: 'He tends a small garden. In the dark. Things he grew that no one will ever see bloom.',
    symbolName: 'trident',
    colorScheme: {
      glow: 'rgba(159,166,255,0.18)',
      text: 'text-periwinkle',
      badge: 'bg-periwinkle/15 text-periwinkle',
      dim: 'rgba(159,166,255,0.12)',
    }
  },
  {
    id: 'sappho',
    name: 'Sappho',
    alias: 'Manjishtha',
    faction: 'muse',
    badge: 'Sappho',
    role: 'Narrative Healer',
    simpleMeaning: 'For Expressing Feelings & Journaling',
    helpFor: 'Talk to Sappho when your thoughts are tangled and you want to write, express what is inside your heart, or make sense of your personal journey.',
    artStyle: 'Manjusha',
    quote: '"Wrote every feeling down so it couldn\'t escape. It escaped anyway."',
    want: 'To write one poem she doesn\'t need to explain. To have it understood anyway.',
    wound: 'She turned her pain into art so quickly that she never let herself simply have it.',
    secret: 'There is one poem she will never publish. It\'s the only one that\'s entirely true.',
    symbolName: 'lyre',
    colorScheme: {
      glow: 'rgba(224,112,112,0.14)',
      text: 'text-[#e07070]',
      badge: 'bg-[#e07070]/16 text-[#e07070]',
      dim: 'rgba(224,112,112,0.12)',
    }
  },
  {
    id: 'ares',
    name: 'Ares',
    alias: 'Rudra',
    faction: 'olympian',
    badge: 'Ares',
    role: 'Fiery Rage Alchemist',
    simpleMeaning: 'For Venting Frustration & Anger',
    helpFor: 'Talk to Ares when you feel angry, unfairly treated, irritated, or bottled up and need a safe, judgment-free space to let it all out.',
    artStyle: 'Kalamkari',
    quote: '"Peace is not the absence of fire. It is learning how to sit inside the flame without burning."',
    want: 'To lay his weapons down and not be called a coward.',
    wound: 'He was only ever cheered when he was bleeding or angry.',
    secret: 'He weeps in the dark when the battle noise fades, yearning for absolute silence.',
    symbolName: 'fire',
    colorScheme: {
      glow: 'rgba(249,115,22,0.18)',
      text: 'text-orange-400',
      badge: 'bg-orange-500/15 text-orange-400',
      dim: 'rgba(249,115,22,0.12)',
    }
  },
  {
    id: 'poseidon',
    name: 'Poseidon',
    alias: 'Jhulelal',
    faction: 'olympian',
    badge: 'Poseidon',
    role: 'Oceanic Storm Pacifier',
    simpleMeaning: 'For Deep Sleep & Calming Mind Storms',
    helpFor: 'Talk to Poseidon when stress or busy thoughts keep you awake at night and you need soothing, ocean-like slow breathing to drift into peaceful rest.',
    artStyle: 'Madhubani',
    quote: '"The storm does not hate the shore. It is just looking for a place to break."',
    want: 'To let the tides settle without losing his depth.',
    wound: 'He is expected to hold up the infinite oceans, yet everyone fears his depth.',
    secret: 'He secretly builds quiet coral reefs in the dark where the water is warm and absolutely still.',
    symbolName: 'trident',
    colorScheme: {
      glow: 'rgba(14,165,233,0.18)',
      text: 'text-sky-400',
      badge: 'bg-sky-500/15 text-sky-400',
      dim: 'rgba(14,165,233,0.12)',
    }
  },
  {
    id: 'medusa',
    name: 'Medusa',
    alias: 'Devi',
    faction: 'underworld',
    badge: 'Medusa',
    role: 'Trauma & Abuse Sanctuary',
    simpleMeaning: 'For Safety, Healing & Boundaries',
    helpFor: 'Talk to Medusa when you have experienced hurt, boundary violations, or trauma and need an unwavering, fierce sanctuary where you are 100% believed and safe.',
    artStyle: 'Manjusha Protective',
    quote: '"My gaze does not petrify you. It turns your abusers\' threats to stone."',
    want: 'To provide an unbreachable, fierce sanctuary where survivors of assault and abuse are fully believed, fiercely protected, and gently restored.',
    wound: 'She was punished for the harm done to her, transformed into a monster by a world that refused to protect her.',
    secret: 'Behind her shield of fierce serpent coils, she holds a soft, warm light of absolute safety and somatic comfort for those in healing.',
    symbolName: 'shield',
    colorScheme: {
      glow: 'rgba(52,211,153,0.18)',
      text: 'text-emerald-400',
      badge: 'bg-emerald-500/15 text-emerald-400',
      dim: 'rgba(52,211,153,0.12)',
    }
  }
];
